metrics: true
ui:
  header: STFC Cloud Status Page
  link: http://status-openstack.stfc.ac.uk/
  logo: https://raw.githubusercontent.com/stfc/stfc-gatus-status/refs/heads/main/assets/UKRI_STFC_Square_RGB.png
  buttons:
    - name: "STFC Cloud Slack"
      link: "https://stfc-cloud.slack.com"
    - name: "Join our Mailing List"
      link: "https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=STFC-CLOUD"
  title: STFC Cloud Status Page
  description: Public status page for STFC Cloud services
  default-sort-by: group

# https://www.datetimeapp.com/
# ISO 8601 timestamps (or RFC3339)
# Types:
# outage: Indicates service disruptions or critical issues (red theme)
# warning: Indicates potential issues or important notices (yellow theme)
# information: General information or updates (blue theme)
# operational: Indicates resolved issues or normal operations (green theme)
# none: Neutral announcements with no specific severity (gray theme, default if none are specified)
announcements:
  - timestamp: 2026-07-10T15:00:00.000+00:00
    type: information
    message: | 
      Cloud Outage Week: Outage work completed!    
  - timestamp: 2026-07-06T8:00:00.000+00:00
    type: outage
    message: | 
      Cloud Outage Week: We are performing essential maintenance this week between Monday 6th until Friday 10th July (inclusive) - you may find that OpenStack services and/or virtual machines will be offline and unavailable at times during this week. Read more here: https://stfc.atlassian.net/wiki/spaces/CLOUDKB/pages/1176436850/Advanced+notice+of+upcoming+July+2026+outage+work    
    archived: true
  - timestamp: 2026-06-22T9:00:00.000+00:00
    type: information
    message: |
      Cinder Volume I/O and FSCK Issues: We are aware of an incident where cinder volumes are failing to mount or are experiencing I/O issues with blocked writes following the RAL power incident. If you are experiencing this please open a ticket to cloud-support@stfc.ac.uk with the volume ID and Name   
    archived: true
  - timestamp: 2026-06-19T9:00:00.000+00:00
    type: information
    message: |
      RAL Power Blip: We have recovered from data-centre power incident that occurred 18/06/2026. You may find your VMs are shutoff, you are free to start them up yourselves. Please open a ticket to cloud-support@stfc.ac.uk if you are experiencing any issues 
    archived: true
  - timestamp: 2026-04-29T12:00:00.000+00:00
    type: information
    message: |
      Upcoming planned outage work for essential maintenance between the 6th and the 10th of July (inclusive), as per our list of important upcoming dates: https://stfc.atlassian.net/wiki/spaces/CLOUDKB/pages/982548867/Important+DatesDuring this window. OpenStack services and/or virtual machines will be offline and unavailable. Users should make alternative arrangements in advance for this entire maintenance window.
    archived: true
  - timestamp: 2026-03-18T12:00:00.000+00:00
    type: information
    message : |
      Upcoming At-Risk Period scheduled for 30th March to 2nd April. This will result in the Cloud operating at risk during this time, whilst we carry out essential work on the Cloud control plane which will allow the continued development of STFC Cloud services. We do not anticipate interruption to STFC Cloud services; however any intervention carries some risk of disruption, hence the operating at risk during this time. Please see the following link for details on these days: https://stfc.atlassian.net/wiki/spaces/CLOUDKB/pages/1125154840/2026+-+30th+March+to+2nd+April+-+At+Risk If you have any questions or concerns about this work, please contact us via cloud-support@stfc.ac.uk
    archived: true
  - timestamp: 2025-12-09T17:00:00.000+00:00
    type: information
    message: |
      The STFC Cloud Operations Group will be providing a reduced service from the 18th of December due to staff being on leave leading up to Christmas. No support will be provided between the 25th of December and the 4th of January, with normal support resuming on January 5th. We will be providing our usual out of hours on call service during this period to respond to platform level critical issues. User communities should visit our linked Slack channel above and view the #notifications channel.
    archived: true
  - timestamp: 2025-10-31T08:00:00.000+00:00
    type: information
    message: |
      Upcoming electrical maintenance works are planned for the weekends of the 1st and 2nd, and 8th and 9th, of November. While this and further planned maintenance works on our Control Plane and Network infrastructure take place, the cloud will be operating at-risk for the period beginning Friday 31st October through to Wednesday 12th November. For more information, included a list of impacted VM types, users should visit our Slack linked above and view the #notifications channel.
    archived: true
storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
